---
- name: Update pkgs cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 

- name: Install strongswan
  apt:
    name: strongswan=5.8.2-1ubuntu3.4

- name: Set sysctl config
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  with_dict: '{{ sysctl_config | items2dict }}'

- name: Copy ipsec client conf
  template:
    src: ipsec-client.conf.j2
    dest: /etc/ipsec.conf
  delegate_to: ipsec-client
  notify: restart strongswan
  register: ipsec-conf

- name: Copy ipsec server conf
  template:
    src: ipsec-server.conf.j2
    dest: /etc/ipsec.conf
  delegate_to: ipsec_server
  notify: Restart strongswan
  register: ipsec-conf
  
- name: Copy ipsec secret key
  template:
    src: ipsec-secret.j2
    dest: /etc/ipsec.secrets
  notify: restart strongswan
  register: ipsec_conf

- name: Run ipsec connect with server
  command: ipsec up l2tpvpn
  delegate_to: ipsec-client
  when: ipsec-conf.changed