---
- name: Update pkgs cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 

- name: Install strongswan
  apt:
    name: strongswan=5.8.2-1ubuntu3.4

- name: Set sysctl config
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  with_dict: '{{ sysctl_config | items2dict }}'

- name: Copy ipsec client conf
  template:
    src: ipsec-client.conf.j2
    dest: /etc/ipsec.conf
  delegate_to: ipsec-client
  delegate_facts: True
  notify: Restart strongswan

- name: Copy ipsec server conf
  template:
    src: ipsec-server.conf.j2
    dest: /etc/ipsec.conf
  delegate_to: ipsec-server
  delegate_facts: True
  notify: Restart strongswan
  
- name: Copy ipsec clients secret key
  template:
    src: ipsec-secret-clients.j2
    dest: /etc/ipsec.secrets
  notify: Restart strongswan
  delegate_to: ipsec-client
  delegate_facts: True

- name: Copy ipsec server secret key
  template:
    src: ipsec-secret-servers.j2
    dest: /etc/ipsec.secrets
  notify: Restart strongswan
  delegate_to: ipsec-server
  delegate_facts: True
